version: '3.9'

networks:
  iced-latte-network:
    name: iced-latte-network
    attachable: true

volumes:
  pg_data:
  nginx_data:
  backend_logs: {}

services:
  iced-latte-backend:
    image: 'zufarexplainedit/iced-latte-backend:latest'
    container_name: iced-latte-backend
    environment:
      APP_SERVER_PORT: 8083
      APP_JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      APP_JWT_REFRESH_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      DATASOURCE_PORT: 5432
      DATASOURCE_NAME: testdb
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      DATASOURCE_HOST: iced-latte-postgresdb
      REDIS_HOST: iced-latte-redis
      REDIS_PORT: 6380
      AWS_DEFAULT_PRODUCT_IMAGES_PATH: ./products
      AWS_ACCESS_KEY: vbfgngfdndgndgndgndgndgndgndg
      AWS_SECRET_KEY: vbfgngfdndgndgndgndgndgndgndg
      AWS_REGION: eu-west-1
      AWS_PRODUCT_BUCKET: products
      AWS_USER_BUCKET: users
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '8083:8083'
      - '5005:5005'
    networks:
      - iced-latte-network
    depends_on:
      - iced-latte-postgresdb
    volumes:
      - backend_logs:/usr/app/logs
      - ./products:/usr/app/products
    restart: on-failure

  iced-latte-postgresdb:
    image: 'postgres:13.11-bullseye'
    container_name: iced-latte-postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    networks:
      - iced-latte-network
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure

  iced-latte-nginx:
    image: nginx:alpine
    container_name: iced-latte-nginx
    volumes:
      - ./nginx_data:/etc/nginx/conf.d:ro
    ports:
      - '80:80'
    networks:
      - iced-latte-network
    depends_on:
      - iced-latte-backend
    restart: on-failure

  iced-latte-redis:
    image: redis/redis-stack:latest
    container_name: iced-latte-redis
    networks:
      - iced-latte-network
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6380
    ports:
      - "6380:6380"
