version: '3.9'

networks:
  online-store-network:
    name: '${DOCKER_COMPOSE_NETWORK}'

services:
  postgresdb:
    image: 'postgres:13.11-bullseye'
    container_name: online-store-postgresdb
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
      - POSTGRES_DB=${APP_SERVER_PORT}
    ports:
      - '${DATASOURCE_PORT}:${DATASOURCE_PORT}'
    networks:
      - '${DOCKER_COMPOSE_NETWORK}'
    volumes:
      - /opt/docker/online-store/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5