openapi: "3.0.3"
info:
  title: "Online_Store API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8083"
tags:
  - name: "Product"
    description: "An API for managing and retrieving product information"
paths:
  /api/v1/products/{productId}:
    get:
      tags:
        - "Product"
      summary: "Enables to get a product by its id"
      operationId: "getProductById"
      parameters:
        - name: "productId"
          description: "the identifier of the product which is returned as the return value"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductInfoDto"
  /api/v1/products:
    get:
      tags:
        - "Product"
      summary: "Enables to get the product list with pagination and sorting features"
      operationId: "getProducts"
      parameters:
        - name: "page"
          description: "page number in order (starting from 0)"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: "0"
        - name: "size"
          description: "number of products in the output"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: "50"
        - name: "sort_attribute"
          description: "the name of the product field by which they should be sorted"
          in: "query"
          required: false
          schema:
            type: "string"
            default: "name"
        - name: "sort_direction"
          description: "sorting direction (DESC or ASC)"
          in: "query"
          required: false
          schema:
            type: "string"
            default: "desc"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductListWithPaginationInfoDto"
components:
  schemas:
    ProductInfoDto:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        name:
          type: "string"
        description:
          type: "string"
        price:
          type: "number"
          format: "decimal"
        quantity:
          type: "integer"
          format: "int32"
    ProductListWithPaginationInfoDto:
      type: "object"
      properties:
        products:
          type: "array"
          items:
            $ref: "#/components/schemas/ProductInfoDto"
        page:
          type: "integer"
          format: "int32"
        size:
          type: "integer"
          format: "int32"
        totalElements:
          type: "integer"
          format: "int64"
        totalPages:
          type: "integer"
          format: "int32"
    ApiResponse:
      type: "object"
      properties:
        data:
          type: "object"
        message:
          type: "string"
        httpStatusCode:
          type: "integer"
        timestamp:
          type: "string"
          format: "date-time"